source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '6.0'
pod 'libpd', '~> 0.7'
pod 'CocoaAsyncSocket', '~> 7.3'
pod 'CocoaLumberjack', '~> 1.8'
pod 'CHCSVParser', '~> 2.1'
pod 'MBProgressHUD', '~> 0.9'
